scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: false
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="blackbox"}'
        - '{__name__=~"probe:.*"}'

    static_configs:
      - targets: ['${prom_addr1}:9090']
        labels:
          job: '${region1}'
      - targets: ['${prom_addr2}:9090']
        labels:
          job: '${region2}'
